name: Building New Kernel

on: [push]

env:
  GIT_SECRETB: ${{ secrets.GIT_SECRETB }}
  GIT_SECRET: ${{ secrets.GIT_SECRET }}
  BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
  GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
  ZIP_PASS: ${{ secrets.ZIP_PASS }}
  TZ: Asia/Jakarta
  DEBIAN_FRONTEND: noninteractive

jobs:
  build:

    defaults:
      run:
        shell: bash

    timeout-minutes: 360

    strategy:

        fail-fast: false

        matrix:
          config:
            # - file: blank
